FROM python:3.14-alpine

ENV PYTHONUNBUFFERED=1

ENV PROXY_HOST=0.0.0.0
ENV PROXY_PORT=7000

ENV HEALTH_PORT=4000

ENV SERVICE_HOST=localhost
ENV SERVICE_PORT=3306

ENV MIN_THREADS=3
ENV RETRY_DELAY_SECONDS=1.0

ENV LOG_LEVEL=INFO

ENV USE_SSL=no
# ENV SSL_CERT=proxy.crt

WORKDIR /app

# Install CA certificates
RUN apk add --no-cache ca-certificates && update-ca-certificates

COPY agent.py agent.py

EXPOSE 4000
EXPOSE 7000

CMD ["python", "agent.py"]
